-- Generated by hypr2lua-web.
-- Source: hyprland.conf

hl.config({
  general = {
    gaps_in = 5,
    gaps_out = 10,
    border_size = 2,
    col = {
      active_border = "rgba(f200f3ff)",
      inactive_border = "rgba(4a2e4aaa)",
    },
    layout = "dwindle",
  },
  decoration = {
    active_opacity = 0.95,
    inactive_opacity = 0.85,
    rounding = 7,
    blur = {
      enabled = true,
      size = 8,
      passes = 3,
      noise = 0.0,
      contrast = 1.07,
      brightness = 0.83,
      vibrancy = 0.23,
      vibrancy_darkness = 0.75,
    },
    shadow = {
      enabled = true,
      range = 10,
      render_power = 2,
      color = "rgba(00000055)",
    },
  },
  animations = {
    enabled = true,
  },
})

hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })

hl.animation({
  leaf = "windows",
  enabled = true,
  speed = 5,
  bezier = "easeOutQuint",
})
hl.animation({
  leaf = "windowsOut",
  enabled = true,
  speed = 6,
  bezier = "easeOutQuint",
  style = "popin 80%",
})
hl.animation({
  leaf = "border",
  enabled = true,
  speed = 10,
  bezier = "default",
})
hl.animation({
  leaf = "fade",
  enabled = true,
  speed = 5,
  bezier = "easeOutQuint",
})
hl.animation({
  leaf = "workspaces",
  enabled = true,
  speed = 4,
  bezier = "easeOutQuint",
})
