#   ____  __  ______   __________  _   __#
#  / __ \/  |/  /   | / ____/ __ \/ | / /#
# / / / / /|_/ / /| |/ /   / / / /  |/ / #
#/ /_/ / /  / / ___ / /___/ /_/ / /|  /  #
#\____/_/  /_/_/  |_\____/\____/_/ |_/   #



# --------------- GENERAL ---------------

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2

    col.active_border = rgba(f200f3ff)
    col.inactive_border = rgba(4a2e4aaa)

    layout = dwindle
}

# --------------- DECORATION ---------------

decoration {

    active_opacity = 0.95
    inactive_opacity = 0.85
    rounding = 7

    blur {
        enabled = true
        size = 3
        passes = 2
        noise = 0.0
        contrast = 1.0
        brightness = 1.0
        vibrancy = 0.10
        vibrancy_darkness = 0.5
    }

    shadow {
        enabled = true
        range = 10
        render_power = 2
        color = rgba(00000055)
    }

        blur {
        enabled = true
        size = 8
        passes = 3
        noise = 0.03
        contrast = 1.07
        brightness = 0.83
        vibrancy = 0.23
        vibrancy_darkness = 0.75
    }

}

# --------------- ANIMATIONS ---------------

animations {
    enabled = true

    bezier = easeOutQuint, 0.23, 1, 0.32, 1

    animation = windows, 1, 5, easeOutQuint
    animation = windowsOut, 1, 6, easeOutQuint, popin 80%
    animation = border, 1, 10, default
    animation = fade, 1, 5, easeOutQuint
    animation = workspaces, 1, 4, easeOutQuint
}
