background            #130c2b
foreground            #f5caff

cursor                #f5caff
selection_foreground  #130c2b
selection_background  #ffbcff

color0  #130c2b
color8  #9e9e9e

color1  #f200f3
color9  #ff66ff

color2  #8467ff
color10 #ac7dff

color3  #ffbcff
color11 #f5caff

color4  #8563ff
color12 #ac7dff

color5  #ff66ff
color13 #ff80ff

color6  #8361ff
color14 #aa7bff

color7  #f5caff
color15 #ffffff
